FROM node:24 AS build
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm install --no-package-lock
COPY ./ ./
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]